/**
 * Mock movie catalog for Viewesta — African cinema streaming.
 * Includes: age_rating, cast_crew with photos, cover (16:9), approval_status.
 * TODO: Replace with API call to GET /movies when backend is ready.
 */

export const mockMovies = [
  {
    id: '1',
    title: 'Lionheart',
    year: 2018,
    rating: 6.4,
    duration: 95,
    genres: ['Drama', 'Comedy', 'Family'],
    director: 'Genevieve Nnaji',
    cast: ['Genevieve Nnaji', 'Nkem Owoh', 'Pete Edochie'],
    description: 'Adaeze must step up to save her father\'s company when her uncle fails to run it properly. A story of family, business, and courage in modern Nigeria.',
    poster: 'https://images.unsplash.com/photo-1486175060817-5664c8d73dc5?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Movie',
    monetization_type: 'subscription',
    age_rating: 'PG',
    cover: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=Lionheart%202018%20official%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Genevieve Nnaji', role: 'Director', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
      { name: 'Genevieve Nnaji', role: 'Actress', character: 'Adaeze', photo: 'https://randomuser.me/api/portraits/women/52.jpg' },
      { name: 'Nkem Owoh', role: 'Actor', character: 'Godswill', photo: 'https://randomuser.me/api/portraits/men/45.jpg' },
      { name: 'Pete Edochie', role: 'Actor', character: 'Ernest', photo: 'https://randomuser.me/api/portraits/men/52.jpg' },
    ],
    release_date: '2018-09-07',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-1',
  },
  {
    id: '2',
    title: 'The Wedding Party',
    year: 2016,
    rating: 5.9,
    duration: 102,
    genres: ['Comedy', 'Romance'],
    director: 'Kemi Adetiba',
    cast: ['Adesua Etomi', 'Banky W', 'Solange Knowles'],
    description: 'A lavish Nigerian wedding turns chaotic as family drama, ex-lovers, and unexpected guests collide in this hit Nollywood comedy.',
    poster: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Movie',
    monetization_type: 'pay_per_view',
    age_rating: 'PG-13',
    cover: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=The%20Wedding%20Party%20Nollywood%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Kemi Adetiba', role: 'Director', photo: 'https://randomuser.me/api/portraits/women/28.jpg' },
      { name: 'Adesua Etomi', role: 'Actress', character: 'Dunni', photo: 'https://randomuser.me/api/portraits/women/60.jpg' },
      { name: 'Banky W', role: 'Actor', character: 'Dozie', photo: 'https://randomuser.me/api/portraits/men/22.jpg' },
      { name: 'Sola Sobowale', role: 'Actress', character: 'Mama Dunni', photo: 'https://randomuser.me/api/portraits/women/35.jpg' },
    ],
    release_date: '2016-12-16',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
  },
  {
    id: '3',
    title: 'King of Boys',
    year: 2018,
    rating: 7.2,
    duration: 180,
    genres: ['Crime', 'Drama', 'Thriller'],
    director: 'Kemi Adetiba',
    cast: ['Sola Sobowale', 'Adesua Etomi', 'Remilekun Reminisce'],
    description: 'Alhaja Eniola Salami fights to retain her empire in the underworld of Lagos in this gripping political thriller.',
    poster: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Movie',
    monetization_type: 'both',
    age_rating: 'R',
    cover: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=King%20of%20Boys%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Kemi Adetiba', role: 'Director', photo: 'https://randomuser.me/api/portraits/women/71.jpg' },
      { name: 'Sola Sobowale', role: 'Actress', character: 'Eniola Salami', photo: 'https://randomuser.me/api/portraits/women/50.jpg' },
      { name: 'Adesua Etomi', role: 'Actress', character: 'Kemi', photo: 'https://randomuser.me/api/portraits/women/62.jpg' },
      { name: 'Reminisce', role: 'Actor', character: 'Makanaki', photo: 'https://randomuser.me/api/portraits/men/33.jpg' },
    ],
    release_date: '2018-10-26',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
  },
  {
    id: '4',
    title: 'Living in Bondage: Breaking Free',
    year: 2019,
    rating: 6.8,
    duration: 121,
    genres: ['Thriller', 'Drama', 'Horror'],
    director: 'Ramsey Nouah',
    cast: ['Kenneth Okonkwo', 'Ramsey Nouah', 'Munachi Abii'],
    description: 'The sequel to the classic Nollywood film. A young man is lured into a secret cult with devastating consequences.',
    poster: 'https://images.unsplash.com/photo-1516916759473-600c07bc12d4?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1280&h=720&fit=crop',
    trending: false,
    featured: true,
    type: 'Movie',
    age_rating: '16+',
    cover: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=Living%20in%20Bondage%20Breaking%20Free%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Ramsey Nouah', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
      { name: 'Kenneth Okonkwo', role: 'Actor', character: 'Andy', photo: 'https://randomuser.me/api/portraits/men/37.jpg' },
      { name: 'Ramsey Nouah', role: 'Actor', character: 'Richard', photo: 'https://randomuser.me/api/portraits/men/63.jpg' },
      { name: 'Munachi Abii', role: 'Actress', character: 'Nnenna', photo: 'https://randomuser.me/api/portraits/women/29.jpg' },
    ],
    release_date: '2019-11-08',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-1',
  },
  {
    id: '5',
    title: 'Òlòturé',
    year: 2019,
    rating: 7.0,
    duration: 106,
    genres: ['Drama', 'Thriller'],
    director: 'Kenneth Gyang',
    cast: ['Sharon Ooja', 'Omowunmi Dada', 'Omoni Oboli'],
    description: 'A journalist goes undercover to expose the trafficking of young women from Nigeria to Europe. A harrowing and powerful drama.',
    poster: 'https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1440404653325-ab3d67dfb6e4?w=1280&h=720&fit=crop',
    trending: true,
    featured: false,
    type: 'Movie',
    age_rating: 'R',
    cover: 'https://images.unsplash.com/photo-1440404653325-ab3d67dfb6e4?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=Oloture%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Kenneth Gyang', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/40.jpg' },
      { name: 'Sharon Ooja', role: 'Actress', character: 'Òlòturé', photo: 'https://randomuser.me/api/portraits/women/66.jpg' },
      { name: 'Omowunmi Dada', role: 'Actress', character: 'Ehi', photo: 'https://randomuser.me/api/portraits/women/28.jpg' },
      { name: 'Omoni Oboli', role: 'Actress', character: 'Alero', photo: 'https://randomuser.me/api/portraits/women/60.jpg' },
    ],
    release_date: '2019-10-04',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
  },
  {
    id: '6',
    title: 'Sugar Rush',
    year: 2019,
    rating: 5.5,
    duration: 115,
    genres: ['Comedy', 'Drama'],
    director: 'Kayode Kasum',
    cast: ['Adesua Etomi', 'Bisola Aiyeola', 'Buju Banton'],
    description: 'Three sisters discover their late father left them a fortune — but they must find it before their stepmother does.',
    poster: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=1280&h=720&fit=crop',
    trending: false,
    featured: false,
    type: 'Movie',
    age_rating: 'PG-13',
    cover: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=Sugar%20Rush%202019%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Kayode Kasum', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/58.jpg' },
      { name: 'Adesua Etomi', role: 'Actress', character: 'Sola', photo: 'https://randomuser.me/api/portraits/women/52.jpg' },
      { name: 'Bisola Aiyeola', role: 'Actress', character: 'Bisi', photo: 'https://randomuser.me/api/portraits/women/35.jpg' },
      { name: 'Bimbo Ademoye', role: 'Actress', character: 'Tola', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
    ],
    release_date: '2019-12-25',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
  },
  {
    id: '7',
    title: 'The Milkmaid',
    year: 2020,
    rating: 6.9,
    duration: 137,
    genres: ['Drama', 'War'],
    director: 'Desmond Ovbiagele',
    cast: ['Anthonieta Kalunta', 'Maryam Booth', 'Gambo Usman'],
    description: 'In rural Nigeria, a Fulani milkmaid searches for her sister after insurgents attack their village. Nigeria\'s Oscar submission.',
    poster: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Movie',
    age_rating: '16+',
    cover: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=The%20Milkmaid%20Nigeria%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Desmond Ovbiagele', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/22.jpg' },
      { name: 'Anthonieta Kalunta', role: 'Actress', character: 'Zainab', photo: 'https://randomuser.me/api/portraits/women/29.jpg' },
      { name: 'Maryam Booth', role: 'Actress', character: 'Hauwa', photo: 'https://randomuser.me/api/portraits/women/66.jpg' },
      { name: 'Gambo Usman', role: 'Actor', character: 'Babakura', photo: 'https://randomuser.me/api/portraits/men/37.jpg' },
    ],
    release_date: '2020-10-08',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-1',
  },
  {
    id: '8',
    title: 'Rattlesnake: The Ahanna Story',
    year: 2020,
    rating: 6.2,
    duration: 130,
    genres: ['Crime', 'Drama', 'Thriller'],
    director: 'Ramsey Nouah',
    cast: ['Stan Nze', 'Osas Ighodaro', 'Chidi Mokeme'],
    description: 'A young man is drawn into a life of crime in 1990s Lagos. A remake of the 1995 classic.',
    poster: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1468421870903-ef3bfb0722a4?w=1280&h=720&fit=crop',
    trending: false,
    featured: false,
    type: 'Movie',
    age_rating: 'R',
    cover: 'https://images.unsplash.com/photo-1468421870903-ef3bfb0722a4?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=Rattlesnake%20The%20Ahanna%20Story%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Ramsey Nouah', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/63.jpg' },
      { name: 'Stan Nze', role: 'Actor', character: 'Ahanna', photo: 'https://randomuser.me/api/portraits/men/55.jpg' },
      { name: 'Osas Ighodaro', role: 'Actress', character: 'Amaka', photo: 'https://randomuser.me/api/portraits/women/60.jpg' },
      { name: 'Chidi Mokeme', role: 'Actor', character: 'Nze', photo: 'https://randomuser.me/api/portraits/men/45.jpg' },
    ],
    release_date: '2020-11-13',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
  },
  {
    id: '9',
    title: 'Ayinla',
    year: 2021,
    rating: 6.5,
    duration: 120,
    genres: ['Biography', 'Drama', 'Music'],
    director: 'Tunde Kelani',
    cast: ['Lateef Adedimeji', 'Bimbo Manuel', 'Kunle Afolayan'],
    description: 'The life and tragic death of Ayinla Omowura, one of Nigeria\'s most influential Apala musicians.',
    poster: 'https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1280&h=720&fit=crop',
    trending: false,
    featured: true,
    type: 'Movie',
    age_rating: '16+',
    cover: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=Ayinla%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Tunde Kelani', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/40.jpg' },
      { name: 'Lateef Adedimeji', role: 'Actor', character: 'Ayinla', photo: 'https://randomuser.me/api/portraits/men/58.jpg' },
      { name: 'Bimbo Manuel', role: 'Actor', character: 'Manager', photo: 'https://randomuser.me/api/portraits/men/33.jpg' },
      { name: 'Kunle Afolayan', role: 'Actor', character: 'Alhaji', photo: 'https://randomuser.me/api/portraits/men/37.jpg' },
    ],
    release_date: '2021-06-18',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
  },
  {
    id: '10',
    title: 'Anikulapo',
    year: 2022,
    rating: 6.7,
    duration: 140,
    genres: ['Drama', 'Fantasy', 'Romance'],
    director: 'Kunle Afolayan',
    cast: ['Kunle Remi', 'Bimbo Ademoye', 'Sola Sobowale'],
    description: 'A stranger gifted with the power to resurrect the dead finds love and betrayal in the ancient Oyo Kingdom.',
    poster: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=400&h=600&fit=crop',
    backdrop: 'https://images.unsplash.com/photo-1493804714600-6edb1cd93080?w=1280&h=720&fit=crop',
    trending: true,
    featured: true,
    type: 'Movie',
    age_rating: '16+',
    cover: 'https://images.unsplash.com/photo-1493804714600-6edb1cd93080?w=1280&h=720&fit=crop',
    trailer_url: 'https://www.youtube.com/embed?listType=search&list=Anikulapo%20trailer&autoplay=0&rel=0',
    approval_status: 'published',
    cast_crew: [
      { name: 'Kunle Afolayan', role: 'Director', photo: 'https://randomuser.me/api/portraits/men/40.jpg' },
      { name: 'Kunle Remi', role: 'Actor', character: 'Saro', photo: 'https://randomuser.me/api/portraits/men/58.jpg' },
      { name: 'Bimbo Ademoye', role: 'Actress', character: 'Arolake', photo: 'https://randomuser.me/api/portraits/women/44.jpg' },
      { name: 'Sola Sobowale', role: 'Actress', character: 'Iyabo', photo: 'https://randomuser.me/api/portraits/women/50.jpg' },
    ],
    release_date: '2022-09-30',
    pricing: { '480p': 2.99, '720p': 4.99, '1080p': 7.99, '4K': 12.99 },
    filmmakerId: 'filmmaker-2',
  },
];
